# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Your awesome title
email: your-email@example.com
locale: en-US
date_format: "%B %-d, %Y"
read_time: true
words_per_minute: 200
mathjax: true
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"
description: >- # this means to ignore newlines until "baseurl:"
  sample description ...
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
# theme: jekyll-theme-so-simple
remote_theme: "mmistakes/so-simple-theme"
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-paginate

paginate: 10
paginate_path: /page:num/

permalink: /:categories/:title/
markdown: kramdown
feed:
  path: atom.xml

# category_archive_path: "/categories/#"
# tag_archive_path: "/tags/#"

collections:
- snippets

collections:
  snippets:
    output: true

# defaults:
#   - scope:
#       path: "_posts"
#       type: posts
#     values:
#       layout: post
#   - scope:
#       path: "_snippets"
#       type: snippets
#     values:
#       layout: collection

# Collections
